#!/usr/bin/env python3
"""Generate stdlib/hpack_huffman.esk — the HPACK Huffman code table (RFC 7541
Appendix B) — from the authoritative RFC text, so the 257-entry table is never
hand-transcribed.

Usage:
    curl -s https://www.rfc-editor.org/rfc/rfc7541.txt | python3 tools/gen_hpack_huffman.py > stdlib/hpack_huffman.esk

Each Appendix B row looks like:
    '/' ( 47)  |011000                                       18  [ 6]
    ( 256)  EOS ...                                     3fffffff  [30]
We take the parenthesized decimal as the symbol index, the bracketed decimal as
the bit length, and the hex token immediately before the bracket as the code.
"""
import sys, re

text = sys.stdin.read()
row = re.compile(r'\(\s*(\d+)\)\s*(?:EOS\s*)?\|?.*?([0-9a-fA-F]+)\s*\[\s*(\d+)\s*\]')
entries = {}
for line in text.splitlines():
    if '[' not in line or '(' not in line:
        continue
    m = row.search(line)
    if not m:
        continue
    idx, hexcode, length = int(m.group(1)), m.group(2), int(m.group(3))
    # Guard: the hex token must be valid for the stated length.
    if int(hexcode, 16) >> length != 0:
        continue
    entries[idx] = (int(hexcode, 16), length)

assert len(entries) == 257, f"expected 257 symbols, parsed {len(entries)}"
assert entries[47] == (0x18, 6), f"symbol 47 mismatch: {entries.get(47)}"   # RFC's worked example
assert entries[256][1] == 30, f"EOS length mismatch: {entries.get(256)}"     # EOS is 30 bits
for i in range(257):
    assert i in entries, f"missing symbol {i}"

out = []
out.append("// hpack_huffman.esk — HPACK Huffman code table (RFC 7541 Appendix B).")
out.append("// GENERATED by tools/gen_hpack_huffman.py from the RFC text — do not edit by hand.")
out.append("// 257 symbols (0..255 plus EOS=256); hpack_huff_code(i) is the LSB-aligned code,")
out.append("// hpack_huff_len(i) its bit length.")
out.append("")
out.append("int64 hpack_huff_code(int i) {")
for i in range(257):
    out.append(f"    if (i == {i}) {{ return (int64){entries[i][0]}; }}")
out.append("    return (int64)0;")
out.append("}")
out.append("")
out.append("int hpack_huff_len(int i) {")
for i in range(257):
    out.append(f"    if (i == {i}) {{ return {entries[i][1]}; }}")
out.append("    return 0;")
out.append("}")
out.append("")
sys.stdout.write("\n".join(out))
