// gen_regex_unicode.go: writes stdlib/regex_unicode.esk, the Unicode tables of
// <regex> (simple case folding, general categories, scripts), from Go's unicode
// package, so <regex> matches Go's regexp (RE2 syntax) on the same Unicode version.
//
//	go run tools/gen_regex_unicode.go > stdlib/regex_unicode.esk
package main

import (
	"fmt"
	"os"
	"sort"
	"strings"
	"unicode"
)

var subcats = []string{"Cc", "Cf", "Co", "Cs", "Ll", "Lm", "Lo", "Lt", "Lu", "Mc", "Me", "Mn",
	"Nd", "Nl", "No", "Pc", "Pd", "Pe", "Pf", "Pi", "Po", "Ps", "Sc", "Sk", "Sm", "So", "Zl", "Zp", "Zs"}

func emitInts(w *strings.Builder, name string, v []int) {
	fmt.Fprintf(w, "const int[%d] %s = {\n", len(v), name)
	for i := 0; i < len(v); i += 12 {
		end := i + 12
		if end > len(v) {
			end = len(v)
		}
		parts := []string{}
		for _, x := range v[i:end] {
			parts = append(parts, fmt.Sprintf("%d", x))
		}
		sep := ","
		if end == len(v) {
			sep = ""
		}
		fmt.Fprintf(w, "    %s%s\n", strings.Join(parts, ", "), sep)
	}
	fmt.Fprintf(w, "};\n")
}

func emitStrs(w *strings.Builder, name string, v []string) {
	fmt.Fprintf(w, "const string[%d] %s = {\n", len(v), name)
	line := "   "
	for i, s := range v {
		item := fmt.Sprintf(" \"%s\"", s)
		if i < len(v)-1 {
			item += ","
		}
		if len(line)+len(item) > 96 {
			fmt.Fprintf(w, "%s\n", line)
			line = "   "
		}
		line += item
	}
	fmt.Fprintf(w, "%s\n};\n", line)
}

func main() {
	var w strings.Builder
	const maxr = unicode.MaxRune
	// Case folding: r -> SimpleFold(r), as runs [lo, hi] with a constant delta, or
	// delta 0 for runs of pairs (lo even offset -> +1, odd offset -> -1).
	type run struct{ lo, hi, d int }
	var runs []run
	for r := 0; r <= maxr; r++ {
		f := int(unicode.SimpleFold(rune(r)))
		if f == r {
			continue
		}
		d := f - r
		if n := len(runs); n > 0 {
			last := &runs[n-1]
			if last.hi == r-1 && last.d == d && d != 1 && d != -1 {
				last.hi = r
				continue
			}
			if last.hi == r-1 && last.d == 0 {
				off := r - last.lo
				if (off%2 == 0 && d == 1) || (off%2 == 1 && d == -1) {
					last.hi = r
					continue
				}
			}
		}
		if d == 1 {
			// start a pair run if the partner maps back
			if int(unicode.SimpleFold(rune(r+1))) == r {
				runs = append(runs, run{r, r, 0})
				continue
			}
		}
		runs = append(runs, run{r, r, d})
	}
	var fold []int
	for _, x := range runs {
		fold = append(fold, x.lo, x.hi, x.d)
	}
	fmt.Fprintf(os.Stderr, "fold runs %d\n", len(runs))

	// General category: start<<8 | id per run (id 255 = unassigned).
	catOf := make([]int, maxr+1)
	for i := range catOf {
		catOf[i] = 255
	}
	for id, name := range subcats {
		t := unicode.Categories[name]
		for r := 0; r <= maxr; r++ {
			if unicode.Is(t, rune(r)) {
				catOf[r] = id
			}
		}
	}
	var cat []int
	prev := -1
	for r := 0; r <= maxr; r++ {
		if catOf[r] != prev {
			cat = append(cat, r<<8|catOf[r])
			prev = catOf[r]
		}
	}
	fmt.Fprintf(os.Stderr, "cat runs %d\n", len(cat))

	// Scripts.
	var names []string
	for n := range unicode.Scripts {
		names = append(names, n)
	}
	sort.Strings(names)
	scOf := make([]int, maxr+1)
	for i := range scOf {
		scOf[i] = 255
	}
	for id, name := range names {
		t := unicode.Scripts[name]
		for _, r16 := range t.R16 {
			for r := int(r16.Lo); r <= int(r16.Hi); r += int(r16.Stride) {
				scOf[r] = id
			}
		}
		for _, r32 := range t.R32 {
			for r := int(r32.Lo); r <= int(r32.Hi); r += int(r32.Stride) {
				scOf[r] = id
			}
		}
	}
	var sc []int
	prev = -1
	for r := 0; r <= maxr; r++ {
		if scOf[r] != prev {
			sc = append(sc, r<<8|scOf[r])
			prev = scOf[r]
		}
	}
	fmt.Fprintf(os.Stderr, "script runs %d names %d\n", len(sc), len(names))

	fmt.Fprintf(&w, "// regex_unicode.esk: the Unicode %s tables of <regex>.\n", unicode.Version)
	fmt.Fprintf(&w, "// GENERATED by tools/gen_regex_unicode.go from Go's unicode package; do not edit by hand.\n\n")
	fmt.Fprintf(&w, "// Simple case folding: triples lo, hi, delta mapping each code point of\n")
	fmt.Fprintf(&w, "// [lo, hi] to the next member of its fold orbit (delta 0: pairs, an even\n")
	fmt.Fprintf(&w, "// offset from lo maps +1 and an odd one -1).\n")
	fmt.Fprintf(&w, "const int RE_NFOLD = %d;\n", len(runs))
	emitInts(&w, "RE_FOLD", fold)
	fmt.Fprintf(&w, "// General category runs: start << 8 | index into RE_CAT_NAMES (255: unassigned).\n")
	fmt.Fprintf(&w, "const int RE_NCATRUN = %d;\n", len(cat))
	emitInts(&w, "RE_CATRUN", cat)
	fmt.Fprintf(&w, "const int RE_NCAT = %d;\n", len(subcats))
	emitStrs(&w, "RE_CAT_NAMES", subcats)
	fmt.Fprintf(&w, "// Script runs: start << 8 | index into RE_SCRIPT_NAMES (255: none).\n")
	fmt.Fprintf(&w, "const int RE_NSCRIPTRUN = %d;\n", len(sc))
	emitInts(&w, "RE_SCRIPTRUN", sc)
	fmt.Fprintf(&w, "const int RE_NSCRIPT = %d;\n", len(names))
	emitStrs(&w, "RE_SCRIPT_NAMES", names)
	fmt.Print(w.String())
}
